######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 14 12:45:06 2013
######################################################################

QT += network 
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CImage.h
SOURCES += CImage.cpp main.cpp
